server {
    listen 80;
    server_name autoon.kr www.autoon.kr;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name autoon.kr www.autoon.kr;

    ssl_certificate /etc/letsencrypt/live/autoon.kr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/autoon.kr/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location /releases/ {
        alias /var/www/releases/;
        autoindex off;
        add_header Content-Disposition attachment;
    }

    location /.well-known/ {
        proxy_pass https://washon-business-842988631270.asia-northeast3.run.app;
        proxy_set_header Host washon-business-842988631270.asia-northeast3.run.app;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_ssl_server_name on;
    }

    location /store/ {
        proxy_pass https://washon-business-842988631270.asia-northeast3.run.app;
        proxy_set_header Host washon-business-842988631270.asia-northeast3.run.app;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_ssl_server_name on;
        proxy_read_timeout 60s;
        proxy_connect_timeout 60s;
    }

    location / {
        proxy_pass https://autoon-home-842988631270.asia-northeast3.run.app;
        proxy_set_header Host autoon-home-842988631270.asia-northeast3.run.app;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_ssl_server_name on;
        proxy_read_timeout 60s;
        proxy_connect_timeout 60s;
    }
}
